### ISSUE TITLE
前辈，请问这个新API，怎么设置全局回调啊？

### ISSUE THREAD

**Issue by sayll** [RubyLouvre/fetch-polyfill#1]
看了文档，就看到新推荐的组件库。貌似之后的主流了，想问全局回调应该怎么设置？
顺便能稍微讲一下大概原理思路吗？小白虚心求教 T T

**Comment by RubyLouvre** [comment]
没有全局回调，这就是fetch的 polyfill啊!

**Comment by sayll** [comment]
现在写的是处理浏览器兼容的代码吗？没有任何扩展功能吗？

**Comment by RubyLouvre** [comment]
只整合 JSONP来跨域,其他不搞
