### ISSUE TITLE
默认http头无法覆盖，导致跨域请求失败

### ISSUE THREAD

**Issue by ken1987** [RubyLouvre/fetch-polyfill#2]
在用七牛服务时，服务器对默认设置的http头x-requested-with不支持。
除了改源码，否则无法覆盖，导致跨域失败。

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/fetch-polyfill/commit/d44fd9bd24bfb101c8b3e1661a83527d062ee39e

修改了一版，你去看看
